# Generated by Django 6.0.7 on 2026-07-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pole',
        ),
    ]
